# Use root/example as user/password credentials
version: '3.1'

services:

  mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example

  redis:
    image: redis:6
    container_name: "redis-server"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    #    command: redis-server --bind redis-container-name --requirepass some-long-password --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    #    environment:
    #      CLICKHOUSE_DB: my_database
    #      CLICKHOUSE_USER: username
    #      CLICKHOUSE_PASSWORD: password
    ports:
      - 6379:6379
    volumes:
      #      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data

    rabbitmq:
      image: rabbitmq:3-management
      container_name: "rabbitmq-server"
      environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin
      #      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: '{ vm_memory_high_watermark, { absolute, "256MiB" } }'
      ports:
        - 15672:15672
        - 5672:5672
        - 5671:5671
      volumes:
        - ./rabbitmq/data:/var/lib/rabbitmq