server:
  port: ${PORT:8083}

## MySQL
replication:
  master:
    url: localhost:4406
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:example}
  slave:
    url: localhost:5506
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:example}

spring:
  application:
    name: social-backend
  jpa:
    hibernate:
      ddl-auto=update:none
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:example}
    initialization-mode: always

  datasource-tarantool:
    jdbc-url: jdbc:tarantool://localhost:3301?user=root&password=example
    host: localhost:3301
    #username=root
    #password=example
  flyway:
    enabled: true
  #spring.datasource.driver-class-name=com.mysql.jdbc.Driver
  #debug=true

  #flyway.baseline-on-migrate=true #used if database has some already table
  #spring.flyway.baseline-on-migrate=true
  #spring.flyway.url=jdbc:mysql://127.0.0.1:3306
  #spring.flyway.user=root
  #spring.flyway.password=example

  thymeleaf:
#    cache: false
#    check-template: true
#    check-template-location: true
    enabled: true
#    encoding: UTF-8
#    mode: HTML
#    prefix: classpath:/templates/
#    suffix: .html
#    servlet:
#      content-type: text/html

#logging:
#  level:
#    org:
#      springframework:
#        jdbc:
#          core:
#            JdbcTemplate: trace
#            namedparam:
#              NamedParameterJdbcTemplate: trace

  # ===============================
  # SERVICE DISCOVERY
  # ===============================
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        enabled: true
        health-check-interval: 10s
#        health-check-path: /consul/health-check
